/**
 * One-time map-building script for Jungle World v1 (does not ship in the game).
 * Outputs:
 *   public/map/jungle-map.json  — Tiled JSON (ground + decor tile layers)
 *   public/map/world-data.json  — spawn, zones, resource nodes, foliage, blocked grid
 *
 * Run: npm run genmap
 */
import fs from 'node:fs';
import path from 'node:path';
import { ARENA_W, ARENA_H } from '../src/content/guardian';

// Frontier expansion (ADR-0009): the map grew 200 → 300 by FAR-EDGE (east+south)
// growth. The original 200×200 CORE is PINNED and generated byte-for-byte as
// before — same RNG order → identical node ids, no save migration. Everything
// under "FRONTIER" below is APPENDED after the core, so core ids never shift.
// CORE_W/CORE_H bound every core-only loop; W/H are the full map.
//
// Realm expansion (ADR-0017 §2): the grid then grew 300 → 384 ONCE, in both
// axes — big enough for all three planned Realm district rects, so the fog
// stride consequence of a width change is paid a single time. The pre-Realm
// 300×300 map is PINNED exactly the way the core was at the last growth:
// PREV_W/PREV_H bound every loop that used to run to the old W/H, and ALL
// district randomness draws from its own separate stream (rng2) — the main
// stream's draw order is untouched, so every pre-existing tile value, node id
// and zone rect stays byte-for-byte identical. See "REALM DISTRICTS" below.
const W = 384;
const H = 384;
const CORE_W = 200;
const CORE_H = 200;
// bounds of the pinned pre-Realm map (the walkable World proper); everything
// beyond is Realm district space sealed in unwalkable void cliff
const PREV_W = 300;
const PREV_H = 300;

// ---------------------------------------------------------------- tileset mapping
// Indices into public/assets/tiles/terrain.png (0-based tile ids; gid = id + 1).
// Finalized against the downloaded tileset — see CREDITS.md.
// These constants are set from the tileset image dimensions:
const TILESET = {
  name: 'terrain',
  image: '../assets/tiles/terrain.png',
  tileSize: 16,
  // 11 downloaded tiles + 9 Mire tiles (mire-tiles.png, tools/compose-mire-tiles.ts).
  // BootScene composes both strips into one canvas texture at runtime, so the
  // downloaded terrain.png is never edited; these dims describe the COMPOSED strip.
  columns: 20,
  imagewidth: 320,
  imageheight: 16,
};

// logical -> tile id (0-based). Arrays = random variants.
const T: Record<string, number[]> = {
  grass: [0, 0, 0, 9, 10],
  water: [1],
  sand: [2],
  dirt: [3],
  swamp: [4],
  cliff: [5],
  stone_floor: [6],
  flower: [7],
  plant: [8],
  // the Sunken Mire strip (ADR-0017 rung 1) — ids 11+ live in mire-tiles.png
  mire_peat: [11, 11, 11, 12, 13],
  mire_water: [14],
  mire_mud: [15],
  mire_flagstone: [16],
  reeds: [17],
  cattails: [18],
  lilypad: [19],
};

// ---------------------------------------------------------------- deterministic RNG
function mulberry32(seed: number) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rng = mulberry32(7);
const rand = (min: number, max: number) => min + rng() * (max - min);
const pick = <T>(arr: T[]): T => arr[Math.floor(rng() * arr.length)];
// Realm districts draw from their OWN stream (ADR-0017): inserting draws into
// the main stream would reshuffle everything generated after them — the
// 200→300 growth taught that lesson for the frontier; districts never touch it.
const rng2 = mulberry32(1017);
const rand2 = (min: number, max: number) => min + rng2() * (max - min);
const pick2 = <T>(arr: T[]): T => arr[Math.floor(rng2() * arr.length)];
// the Hushdark (ADR-0017 rung 2) draws from its OWN third stream so it perturbs
// NEITHER the pinned map (rng) NOR the already-shipped Sunken Mire district (rng2):
// the appended-space tile-variant loop shares rng2, so a new district must add no
// rng2 draws AND no decor there (each of its tiles still draws exactly one pick2,
// same count as the void cliff it replaces), keeping the Mire district byte-stable.
const rng3 = mulberry32(2027);
const rand3 = (min: number, max: number) => min + rng3() * (max - min);
// the Green Terraces (ADR-0017 rung 3) draw from a FOURTH stream so they perturb
// NONE of the pinned map (rng), the Sunken Mire (rng2) or the Hushdark (rng3). The
// district uses NO decor AND NO grass — grass would fire the appended-space decor
// loop's rng2 draws, and decor would add a tile-variant pick — either of which
// would shift the SHARED pick2 sequence the Mire/Hushdark tile variants ride. With
// neither, every Verdant tile still costs exactly ONE pick2 (same as the void cliff
// it replaces), so the rng2 sequence stays byte-for-byte unchanged.
const rng4 = mulberry32(3037);
const rand4 = (min: number, max: number) => min + rng4() * (max - min);

// ---------------------------------------------------------------- grid
type Ground =
  | 'grass'
  | 'water'
  | 'sand'
  | 'dirt'
  | 'swamp'
  | 'cliff'
  | 'stone_floor'
  // the Sunken Mire's palette (district space only — never on the pinned map)
  | 'mire_peat'
  | 'mire_water'
  | 'mire_mud'
  | 'mire_flagstone';

const ground: Ground[][] = Array.from({ length: H }, () => Array<Ground>(W).fill('grass'));
const decor: (string | null)[][] = Array.from({ length: H }, () => Array<string | null>(W).fill(null));

const inBounds = (x: number, y: number) => x >= 0 && y >= 0 && x < W && y < H;

function fillCircle(cx: number, cy: number, r: number, kind: Ground, over?: Ground[]) {
  for (let y = Math.floor(cy - r); y <= cy + r; y++) {
    for (let x = Math.floor(cx - r); x <= cx + r; x++) {
      if (!inBounds(x, y)) continue;
      if ((x - cx) ** 2 + (y - cy) ** 2 <= r * r) {
        if (!over || over.includes(ground[y][x])) ground[y][x] = kind;
      }
    }
  }
}

function fillRect(x0: number, y0: number, w: number, h: number, kind: Ground) {
  for (let y = y0; y < y0 + h; y++) {
    for (let x = x0; x < x0 + w; x++) {
      if (inBounds(x, y)) ground[y][x] = kind;
    }
  }
}

// ---------------------------------------------------------------- authoring

// 1. northern cliff range (frame for the waterfall)
fillRect(0, 0, W, 6, 'cliff');

// 2. waterfall pouring through the cliff into a pool
fillRect(96, 0, 9, 22, 'water');
fillCircle(100, 28, 9, 'water');

// 3. river: pool -> meander south -> delta in the south-west
function carveRiver(points: [number, number][], width: number) {
  for (let i = 0; i < points.length - 1; i++) {
    const [x0, y0] = points[i];
    const [x1, y1] = points[i + 1];
    const steps = Math.ceil(Math.hypot(x1 - x0, y1 - y0) * 2);
    for (let s = 0; s <= steps; s++) {
      const t = s / steps;
      const x = x0 + (x1 - x0) * t + Math.sin(t * Math.PI * 3 + i) * 1.5;
      const y = y0 + (y1 - y0) * t;
      fillCircle(x, y, width, 'water');
    }
  }
}
carveRiver(
  [
    [100, 34],
    [92, 55],
    [80, 75],
    [72, 95],
    [66, 115],
    [58, 135],
    [48, 155],
    [40, 175],
    [34, 199],
  ],
  2.4,
);
// delta branches
carveRiver(
  [
    [58, 135],
    [45, 150],
    [30, 170],
    [22, 199],
  ],
  2.0,
);
carveRiver(
  [
    [48, 155],
    [55, 175],
    [58, 199],
  ],
  1.8,
);

// 4. sunken swamp — south-east
for (let i = 0; i < 26; i++) {
  fillCircle(rand(132, 184), rand(140, 182), rand(1.5, 4.5), 'swamp');
}
for (let i = 0; i < 14; i++) {
  fillCircle(rand(134, 182), rand(142, 180), rand(1, 3), 'water');
}

// 5. ancient ruins — north-east: broken stone floors
for (let i = 0; i < 12; i++) {
  fillCircle(rand(146, 178), rand(20, 52), rand(2, 5), 'stone_floor', ['grass']);
}
fillRect(154, 30, 14, 12, 'stone_floor');

// 6. dirt paths from the spawn clearing to every zone
function carvePath(points: [number, number][]) {
  for (let i = 0; i < points.length - 1; i++) {
    const [x0, y0] = points[i];
    const [x1, y1] = points[i + 1];
    const steps = Math.ceil(Math.hypot(x1 - x0, y1 - y0) * 2);
    for (let s = 0; s <= steps; s++) {
      const t = s / steps;
      const x = Math.round(x0 + (x1 - x0) * t + Math.sin(t * 7 + i * 2) * 1.2);
      const y = Math.round(y0 + (y1 - y0) * t);
      for (let dy = 0; dy <= 1; dy++) {
        for (let dx = 0; dx <= 1; dx++) {
          if (!inBounds(x + dx, y + dy)) continue;
          const g = ground[y + dy][x + dx];
          if (g === 'grass' || g === 'swamp' || g === 'stone_floor') ground[y + dy][x + dx] = 'dirt';
          else if (g === 'water') ground[y + dy][x + dx] = 'sand'; // ford
        }
      }
    }
  }
}
carvePath([
  [100, 100],
  [100, 60],
  [100, 40],
]); // → waterfall
carvePath([
  [100, 100],
  [125, 80],
  [150, 55],
  [162, 38],
]); // → ruins
carvePath([
  [100, 100],
  [130, 100],
  [158, 100],
]); // → dense grove
carvePath([
  [100, 100],
  [120, 130],
  [150, 158],
]); // → swamp
carvePath([
  [100, 100],
  [75, 120],
  [55, 145],
  [42, 160],
]); // → river delta (crosses the river at a ford)
carvePath([
  [100, 100],
  [70, 90],
  [45, 80],
  [32, 75],
]); // → hidden grove entrance

// 6b. the two Quarries — ALL surface stone lives here (tier-2 obsidian aside):
// stone is a place you travel to, not a pebble you trip over. Each is a
// carved stone-floor pit with a dirt rim, ringed inside with rock nodes.
const QUARRIES = [
  { name: 'North Quarry', cx: 124, cy: 30 },
  { name: 'South Quarry', cx: 48, cy: 126 },
];
for (const q of QUARRIES) {
  fillCircle(q.cx, q.cy, 7, 'dirt', ['grass', 'swamp']);
  fillCircle(q.cx, q.cy, 5.5, 'stone_floor', ['grass', 'dirt', 'swamp']);
}
carvePath([
  [100, 100],
  [112, 62],
  [124, 36],
]); // → north quarry
carvePath([
  [75, 120],
  [60, 123],
  [52, 126],
]); // → south quarry (branches off the delta path, fords the river)

// 7. beaches: grass adjacent to water becomes sand
const sandify: [number, number][] = [];
for (let y = 0; y < H; y++) {
  for (let x = 0; x < W; x++) {
    if (ground[y][x] !== 'grass') continue;
    for (const [dx, dy] of [
      [1, 0],
      [-1, 0],
      [0, 1],
      [0, -1],
    ]) {
      if (inBounds(x + dx, y + dy) && ground[y + dy][x + dx] === 'water') {
        sandify.push([x, y]);
        break;
      }
    }
  }
}
for (const [x, y] of sandify) ground[y][x] = 'sand';

// 8. v2: the Guardian's arena — a cliff-walled court in the north-east ruins.
// Terrain is written BEFORE node generation so no node lands inside, and the
// arena consumes no RNG — v1 node ids stay byte-stable for existing saves.
const ARENA = { x: 169, y: 15, w: ARENA_W, h: ARENA_H };
const GUARDIAN_HOME = { tx: ARENA.x + Math.floor(ARENA_W / 2) - 1, ty: ARENA.y + 1 }; // 3x3, top-center
const SEAL_GATE = [ARENA.x + 7, ARENA.x + 8, ARENA.x + 9].map((tx) => ({ tx, ty: ARENA.y + ARENA.h })); // south entrance
for (let y = ARENA.y - 1; y <= ARENA.y + ARENA.h; y++) {
  for (let x = ARENA.x - 1; x <= ARENA.x + ARENA.w; x++) {
    const isWall = x === ARENA.x - 1 || x === ARENA.x + ARENA.w || y === ARENA.y - 1 || y === ARENA.y + ARENA.h;
    ground[y][x] = isWall ? 'cliff' : 'stone_floor';
  }
}
for (const g of SEAL_GATE) ground[g.ty][g.tx] = 'stone_floor'; // the entrance gap the Seal blocks
carvePath([
  [162, 38],
  [170, 34],
  [SEAL_GATE[1].tx, SEAL_GATE[1].ty + 2],
]); // → arena entrance

// 8b. spawn clearing — keep it open
const SPAWN = { tx: 100, ty: 100 };

// ---------------------------------------------------------------- zones
// ADR-0012: each Zone carries a `dangerous` flag. The core (near spawn) + the
// un-zoned Deep Jungle stay a SAFE haven — peaceful Wildlife roams there, but no
// predator ever spawns/attacks (the safe start the Journey assumes). Predators
// live ONLY in the danger-flagged FRONTIER Zones: "combat is something you walk
// into." Adding the field does not touch zoneAt (name-keyed) or the RNG order, so
// every Node id + Zone rect stays byte-stable.
const zones = [
  // quarry zones come first — zoneAt takes the first hit, and both overlap
  // broader zones (the South Quarry sits inside the River Delta rectangle)
  { name: 'North Quarry', x: 116, y: 22, w: 16, h: 16, dangerous: false },
  { name: 'South Quarry', x: 40, y: 118, w: 16, h: 16, dangerous: false },
  { name: 'Spawn Clearing', x: 88, y: 88, w: 24, h: 24, dangerous: false },
  { name: 'Thundering Falls', x: 86, y: 6, w: 30, h: 34, dangerous: false },
  { name: 'Ancient Ruins', x: 140, y: 14, w: 48, h: 44, dangerous: false },
  { name: 'Dense Grove', x: 128, y: 66, w: 62, h: 62, dangerous: false },
  { name: 'Sunken Swamp', x: 126, y: 134, w: 64, h: 56, dangerous: false },
  { name: 'River Delta', x: 12, y: 120, w: 70, h: 74, dangerous: false },
  { name: 'Hidden Grove', x: 6, y: 56, w: 30, h: 40, dangerous: false },
  // ---- FRONTIER zones (ADR-0009), appended after the core. Every rect lies
  // wholly in the east (x>=200) OR south (y>=200) frontier, so no CORE cell
  // (x<200 AND y<200) ever matches one — core zoneAt results are unchanged.
  // These are the danger-flagged WILDS (ADR-0012): predators prowl here.
  { name: 'Highland Crags', x: 224, y: 10, w: 62, h: 72, dangerous: true }, // east-north: the hill + 3rd quarry + vista
  { name: 'Overgrown Temple', x: 214, y: 116, w: 72, h: 76, dangerous: true }, // east-south: tier-2 grove + lore
  { name: 'Mangrove Coast', x: 100, y: 226, w: 108, h: 70, dangerous: true }, // south: fishing + shipwreck treasure
  { name: 'The Cavern Mouth', x: 16, y: 222, w: 80, h: 74, dangerous: true }, // south-west: the Delve entrance
  // ---- REALM district Zones (ADR-0017), appended last. Every rect lies wholly
  // beyond the pinned 300×300 map (x>=300 or y>=300), so no pre-existing tile
  // can ever match one — zoneAt for the old World is unchanged, first-hit order
  // preserved. Deliberately NOT dangerous: predators never spawn in a Realm.
  { name: 'The Sunken Mire', x: 100, y: 300, w: 108, h: 72, dangerous: false }, // rung 1 Realm (T2 stub; T5 fills it in)
  { name: 'The Hushdark', x: 16, y: 300, w: 80, h: 72, dangerous: false }, // rung 2 Realm (ADR-0017; T6)
  { name: 'The Green Terraces', x: 220, y: 300, w: 120, h: 72, dangerous: false }, // rung 3 Realm (ADR-0017; T7)
];

function zoneAt(x: number, y: number): string {
  for (const z of zones) {
    if (x >= z.x && x < z.x + z.w && y >= z.y && y < z.y + z.h) return z.name;
  }
  return 'Deep Jungle';
}

// ---------------------------------------------------------------- resource nodes + foliage
interface NodeOut {
  id: string;
  type: 'tree' | 'rock' | 'fruit_bush' | 'fiber_vine' | 'hardwood_tree' | 'obsidian_rock' | 'fishing_spot' | 'salt_reed_bed' | 'echo_crystal_seam' | 'wildgrain_bed';
  tx: number;
  ty: number;
}

const inArenaOuter = (x: number, y: number) =>
  x >= ARENA.x - 1 && x <= ARENA.x + ARENA.w && y >= ARENA.y - 1 && y <= ARENA.y + ARENA.h;

// ---- ADR-0017 rung 1: the Mire Warden's arena on the Mangrove Coast. It
// replicates the Guardian's arena anatomy (cliff-walled court, colossus home tile
// top-center, offering monument OUTSIDE the south gate, summoning altar INSIDE)
// but is sited in the ALREADY-GENERATED frontier, so — unlike the Guardian's —
// its terrain is carved LATE (after every node/decor draw): the writes consume no
// RNG (variant picks change value, never count) and each footprint node is evicted
// by id via keptNodes, so no pinned node id or tile-variant stream ever shifts.
const MIRE_ARENA = { x: 110, y: 236, w: ARENA_W, h: ARENA_H };
const MIRE_HOME = { tx: MIRE_ARENA.x + Math.floor(ARENA_W / 2) - 1, ty: MIRE_ARENA.y + 1 }; // 3x3, top-center
const MIRE_SEAL_GATE = [MIRE_ARENA.x + 7, MIRE_ARENA.x + 8, MIRE_ARENA.x + 9].map((tx) => ({ tx, ty: MIRE_ARENA.y + MIRE_ARENA.h })); // south Ward gap
const MIRE_ALTAR = { tx: MIRE_ARENA.x + 7, ty: MIRE_ARENA.y + 10 }; // 2 tiles, inside near the gate
const MIRE_MONUMENT = { tx: MIRE_ARENA.x + 7, ty: MIRE_ARENA.y + MIRE_ARENA.h + 2 }; // 2 tiles, outside the gate on the approach
const inMireArenaOuter = (x: number, y: number) =>
  x >= MIRE_ARENA.x - 1 && x <= MIRE_ARENA.x + MIRE_ARENA.w && y >= MIRE_ARENA.y - 1 && y <= MIRE_ARENA.y + MIRE_ARENA.h;
const isMireMonument = (x: number, y: number) =>
  (x === MIRE_MONUMENT.tx || x === MIRE_MONUMENT.tx + 1) && y === MIRE_MONUMENT.ty;

// ---- ADR-0017 rung 2: the Echo Warden's arena in The Cavern Mouth. Same anatomy
// and same LATE, RNG-FREE carve discipline as the Mire arena, sited in the clear
// NW quadrant of the Cavern Mouth — well away from the Delve shaft (56,260), its
// approach column (x≈56–60) and the obsidian veins (x≥38 / y≥252). A stone-floored
// court walled in cliff, its cold blue-steel look supplied scene-side by KIT_ART.
const ECHO_ARENA = { x: 20, y: 224, w: ARENA_W, h: ARENA_H };
const ECHO_HOME = { tx: ECHO_ARENA.x + Math.floor(ARENA_W / 2) - 1, ty: ECHO_ARENA.y + 1 }; // 3x3, top-center
const ECHO_SEAL_GATE = [ECHO_ARENA.x + 7, ECHO_ARENA.x + 8, ECHO_ARENA.x + 9].map((tx) => ({ tx, ty: ECHO_ARENA.y + ECHO_ARENA.h })); // south Ward gap
const ECHO_ALTAR = { tx: ECHO_ARENA.x + 7, ty: ECHO_ARENA.y + 10 }; // inside near the gate
const ECHO_MONUMENT = { tx: ECHO_ARENA.x + 7, ty: ECHO_ARENA.y + ECHO_ARENA.h + 2 }; // 2 tiles, outside the gate
const inEchoArenaOuter = (x: number, y: number) =>
  x >= ECHO_ARENA.x - 1 && x <= ECHO_ARENA.x + ECHO_ARENA.w && y >= ECHO_ARENA.y - 1 && y <= ECHO_ARENA.y + ECHO_ARENA.h;
const isEchoMonument = (x: number, y: number) =>
  (x === ECHO_MONUMENT.tx || x === ECHO_MONUMENT.tx + 1) && y === ECHO_MONUMENT.ty;

// ---- ADR-0017 rung 3: the Verdant Warden's arena in the clear south-east frontier
// grass — below the Overgrown Temple, east of the Mangrove Coast, well clear of
// every other feature. It MUST live in the World (the fight drops terrace_key, the
// key opens the gate, the gate is the only way into the district), so it follows
// the same LATE, RNG-FREE carve discipline as the Mire and Echo arenas: a cliff-
// walled stone court with a south Ward gap. Its green hillside identity is supplied
// scene-side (KIT_ART + ambience veil). The Green Terraces it gates lie south (y>=300).
const VERDANT_ARENA = { x: 268, y: 250, w: ARENA_W, h: ARENA_H };
const VERDANT_HOME = { tx: VERDANT_ARENA.x + Math.floor(ARENA_W / 2) - 1, ty: VERDANT_ARENA.y + 1 }; // 3x3, top-center
const VERDANT_SEAL_GATE = [VERDANT_ARENA.x + 7, VERDANT_ARENA.x + 8, VERDANT_ARENA.x + 9].map((tx) => ({ tx, ty: VERDANT_ARENA.y + VERDANT_ARENA.h })); // south Ward gap
const VERDANT_ALTAR = { tx: VERDANT_ARENA.x + 7, ty: VERDANT_ARENA.y + 10 }; // inside near the gate
const VERDANT_MONUMENT = { tx: VERDANT_ARENA.x + 7, ty: VERDANT_ARENA.y + VERDANT_ARENA.h + 2 }; // 2 tiles, outside the gate
const inVerdantArenaOuter = (x: number, y: number) =>
  x >= VERDANT_ARENA.x - 1 && x <= VERDANT_ARENA.x + VERDANT_ARENA.w && y >= VERDANT_ARENA.y - 1 && y <= VERDANT_ARENA.y + VERDANT_ARENA.h;
const isVerdantMonument = (x: number, y: number) =>
  (x === VERDANT_MONUMENT.tx || x === VERDANT_MONUMENT.tx + 1) && y === VERDANT_MONUMENT.ty;

const nodes: NodeOut[] = [];
const foliage: { kind: string; tx: number; ty: number }[] = [];
const occupied = new Set<string>();

const treeDensity: Record<string, number> = {
  'North Quarry': 0.02,
  'South Quarry': 0.02,
  'Dense Grove': 0.4,
  'Deep Jungle': 0.16,
  'Spawn Clearing': 0.015,
  'Thundering Falls': 0.06,
  'Ancient Ruins': 0.05,
  'Sunken Swamp': 0.09,
  'River Delta': 0.07,
  'Hidden Grove': 0.1,
  // frontier: sparser than the core, but never empty (reward-gradient)
  'Highland Crags': 0.05,
  'Overgrown Temple': 0.16,
  'Mangrove Coast': 0.1,
  'The Cavern Mouth': 0.08,
};
// no scattered rocks: every surface rock node is authored into the two
// Quarries below (tier-2 obsidian keeps its own scattered taunt spots)
const bushDensity: Record<string, number> = {
  'North Quarry': 0.005,
  'South Quarry': 0.005,
  'Spawn Clearing': 0.05,
  'Hidden Grove': 0.22,
  'River Delta': 0.055,
  'Deep Jungle': 0.012,
  'Dense Grove': 0.01,
  'Ancient Ruins': 0.01,
  'Thundering Falls': 0.015,
  'Sunken Swamp': 0.008,
  'Highland Crags': 0.02,
  'Overgrown Temple': 0.02,
  'Mangrove Coast': 0.05,
  'The Cavern Mouth': 0.02,
};
const vineDensity: Record<string, number> = {
  'North Quarry': 0,
  'South Quarry': 0,
  'Sunken Swamp': 0.12,
  'Dense Grove': 0.07,
  'River Delta': 0.02,
  'Deep Jungle': 0.006,
  'Hidden Grove': 0.02,
  'Ancient Ruins': 0.008,
  'Spawn Clearing': 0,
  'Thundering Falls': 0.005,
  'Highland Crags': 0.005,
  'Overgrown Temple': 0.05,
  'Mangrove Coast': 0.06,
  'The Cavern Mouth': 0.02,
};

function nearWater(x: number, y: number): boolean {
  for (let dy = -1; dy <= 1; dy++) {
    for (let dx = -1; dx <= 1; dx++) {
      if (inBounds(x + dx, y + dy) && ground[y + dy][x + dx] === 'water') return true;
    }
  }
  return false;
}

let nodeId = 0;
function tryPlaceNode(type: NodeOut['type'], x: number, y: number): void {
  if (!inBounds(x, y)) return;
  const key = `${x},${y}`;
  if (occupied.has(key)) return;
  const g = ground[y][x];
  // mire_peat/mire_mud only exist in district space, so accepting them cannot
  // change any pinned-map placement outcome; echo_crystal_seam is placed ONLY in
  // the Hushdark district (never during pinned gen), so accepting it on stone_floor
  // cannot change any pinned placement either
  if (
    g !== 'grass' && g !== 'swamp' && g !== 'mire_peat' && g !== 'mire_mud' &&
    !((type === 'rock' || type === 'obsidian_rock') && g === 'stone_floor') &&
    !(type === 'echo_crystal_seam' && g === 'stone_floor')
  )
    return;
  if (Math.abs(x - SPAWN.tx) <= 2 && Math.abs(y - SPAWN.ty) <= 2) return;
  if ((type === 'tree' || type === 'hardwood_tree') && nearWater(x, y)) return;
  occupied.add(key);
  nodes.push({ id: `n${nodeId++}`, type, tx: x, ty: y });
}

// jittered 2x2 grid keeps nodes from clumping into unreadable blobs.
// BOUNDED TO THE CORE: the exact same iteration + RNG sequence as the original
// 200×200 map, so every core node id is byte-stable (frontier nodes append later).
for (let gy = 1; gy < CORE_H - 1; gy += 2) {
  for (let gx = 1; gx < CORE_W - 1; gx += 2) {
    const x = gx + Math.floor(rand(0, 2));
    const y = gy + Math.floor(rand(0, 2));
    if (!inBounds(x, y)) continue;
    const zone = zoneAt(x, y);
    const roll = rng();
    const tree = treeDensity[zone] ?? 0.1;
    const bush = bushDensity[zone] ?? 0.01;
    const vine = vineDensity[zone] ?? 0.005;
    if (roll < tree) tryPlaceNode('tree', x, y);
    else if (roll < tree + bush) tryPlaceNode('fruit_bush', x, y);
    else if (roll < tree + bush + vine) tryPlaceNode('fiber_vine', x, y);
  }
}

// the Quarries' rock clusters — a ring plus an inner scatter, with walkable
// lanes between (placed without RNG, like the v2 nodes, so ids stay stable)
for (const q of QUARRIES) {
  for (const [dx, dy] of [
    [-4, -1], [-3, -3], [-1, -4], [2, -4], [4, -2], [4, 1], [3, 3], [0, 4], [-3, 3],
    [-1, 0], [1, -1], [2, 2], [-2, -2],
  ] as [number, number][]) {
    tryPlaceNode('rock', q.cx + dx, q.cy + dy);
  }
}

// hidden grove: dense tree ring with a single eastern entrance
for (let a = 0; a < Math.PI * 2; a += 0.09) {
  const rx = Math.round(20 + Math.cos(a) * 13);
  const ry = Math.round(75 + Math.sin(a) * 15);
  if (Math.abs(ry - 75) < 3 && rx > 26) continue; // entrance gap
  tryPlaceNode('tree', rx, ry);
  tryPlaceNode('tree', rx + 1, ry);
}

// ruin pillars (decorative, solid) — none inside the v2 arena
const pillarSpots: [number, number][] = [
  [154, 30],
  [167, 30],
  [154, 41],
  [167, 41],
  [148, 24],
  [174, 24],
  [160, 48],
  [150, 50],
];
for (const [x, y] of pillarSpots) {
  if (occupied.has(`${x},${y}`) || inArenaOuter(x, y)) continue;
  occupied.add(`${x},${y}`);
  foliage.push({ kind: 'ruin_pillar', tx: x, ty: y });
}

// ---------------------------------------------------------------- v2 nodes
// Placed AFTER the main loop with no RNG so v1 node ids stay stable.
// Tier-2 nodes are visible from day one and taunt until the tools exist.

/** place at the first valid tile spiralling out from (cx, cy) */
function placeNodeNear(type: NodeOut['type'], cx: number, cy: number, maxR = 8): void {
  for (let r = 0; r <= maxR; r++) {
    for (let dy = -r; dy <= r; dy++) {
      for (let dx = -r; dx <= r; dx++) {
        if (Math.max(Math.abs(dx), Math.abs(dy)) !== r) continue;
        const x = cx + dx;
        const y = cy + dy;
        if (!inBounds(x, y) || inArenaOuter(x, y)) continue;
        const before = nodes.length;
        tryPlaceNode(type, x, y);
        if (nodes.length > before) return;
      }
    }
  }
  console.warn(`! could not place ${type} near ${cx},${cy}`);
}

/** fishing spots sit ON water, castable from an adjacent shore tile */
function placeFishingSpotNear(cx: number, cy: number, maxR = 12): void {
  for (let r = 0; r <= maxR; r++) {
    for (let dy = -r; dy <= r; dy++) {
      for (let dx = -r; dx <= r; dx++) {
        if (Math.max(Math.abs(dx), Math.abs(dy)) !== r) continue;
        const x = cx + dx;
        const y = cy + dy;
        if (!inBounds(x, y) || occupied.has(`${x},${y}`) || (ground[y][x] !== 'water' && ground[y][x] !== 'mire_water')) continue;
        let shore = false;
        for (let ny = -1; ny <= 1 && !shore; ny++) {
          for (let nx = -1; nx <= 1 && !shore; nx++) {
            if (!inBounds(x + nx, y + ny)) continue;
            const g = ground[y + ny][x + nx];
            if (g === 'grass' || g === 'sand' || g === 'dirt' || g === 'stone_floor' || g === 'swamp' || g === 'mire_mud' || g === 'mire_peat' || g === 'mire_flagstone') shore = true;
          }
        }
        if (!shore) continue;
        occupied.add(`${x},${y}`);
        nodes.push({ id: `n${nodeId++}`, type: 'fishing_spot', tx: x, ty: y });
        return;
      }
    }
  }
  console.warn(`! could not place fishing_spot near ${cx},${cy}`);
}

// ancient hardwood trees — scattered so every Zone route passes one
for (const [x, y] of [
  [104, 96], // taunts right at the spawn clearing
  [95, 107],
  [135, 90],
  [150, 105],
  [168, 78],
  [172, 120],
  [60, 60],
  [75, 130],
  [145, 60],
  [88, 32],
  [140, 148],
  [48, 146],
] as [number, number][]) {
  placeNodeNear('hardwood_tree', x, y);
}

// obsidian rocks — clustered toward ruins, cliffs and swamp
for (const [x, y] of [
  [150, 35],
  [160, 44],
  [173, 42],
  [146, 20],
  [90, 10],
  [110, 9],
  [150, 160],
  [165, 175],
  [120, 40],
  [55, 100],
] as [number, number][]) {
  placeNodeNear('obsidian_rock', x, y);
}

// fishing spots — falls pool, river bends, delta branches
for (const [x, y] of [
  [98, 33],
  [104, 29],
  [88, 60],
  [76, 92],
  [68, 112],
  [52, 145],
  [38, 168],
  [56, 178],
  [24, 182],
] as [number, number][]) {
  placeFishingSpotNear(x, y);
}

// ============================================================ FRONTIER (ADR-0009)
// Everything below is APPENDED after the pinned core: every core node id is
// already assigned above, so nothing here can shift them. All authoring stays in
// the frontier (x>=CORE_W OR y>=CORE_H); a helper guards paths against the core.

const inFrontier = (x: number, y: number) => x >= CORE_W || y >= CORE_H;

/** like carvePath, but never writes a CORE tile — keeps existing builds pinned */
function carveFrontierPath(points: [number, number][]) {
  for (let i = 0; i < points.length - 1; i++) {
    const [x0, y0] = points[i];
    const [x1, y1] = points[i + 1];
    const steps = Math.ceil(Math.hypot(x1 - x0, y1 - y0) * 2);
    for (let s = 0; s <= steps; s++) {
      const t = s / steps;
      const x = Math.round(x0 + (x1 - x0) * t + Math.sin(t * 7 + i * 2) * 1.2);
      const y = Math.round(y0 + (y1 - y0) * t);
      for (let dy = 0; dy <= 1; dy++) {
        for (let dx = 0; dx <= 1; dx++) {
          const px = x + dx;
          const py = y + dy;
          if (!inBounds(px, py) || !inFrontier(px, py)) continue;
          const g = ground[py][px];
          if (g === 'grass' || g === 'swamp' || g === 'stone_floor') ground[py][px] = 'dirt';
          else if (g === 'water') ground[py][px] = 'sand';
        }
      }
    }
  }
}

/** the faux-elevation primitive (ADR-0009): what GameScene needs to render a hill */
interface ElevationRegion {
  name: string;
  /** which terrace this is — 1 = first plateau, 2 = a plateau stacked on top, … */
  level: number;
  bounds: { x: number; y: number; w: number; h: number };
  /** walkable plateau-top tiles — entities on these get the elevation depth bump */
  plateau: [number, number][];
  /** cliff-edge tiles (blocked) drawn as a downward face */
  faces: [number, number][];
  /** the sole walkable ascent */
  ramp: [number, number][];
  /** reaching here lifts minimap fog around the crag */
  vista: { tx: number; ty: number };
  /** fog-lift radius in chunks */
  vistaChunkRadius: number;
}
const elevationRegions: ElevationRegion[] = [];

/** carve one terrace rect: cliff-ring border (blocked) + walkable top + one south ramp */
function carveTerrace(name: string, level: number, rect: { x: number; y: number; w: number; h: number }, vistaR: number) {
  const rampX = rect.x + Math.floor(rect.w / 2);
  const plateau: [number, number][] = [];
  const faces: [number, number][] = [];
  const ramp: [number, number][] = [];
  for (let y = rect.y; y < rect.y + rect.h; y++) {
    for (let x = rect.x; x < rect.x + rect.w; x++) {
      if (!inBounds(x, y)) continue;
      const edge = x === rect.x || x === rect.x + rect.w - 1 || y === rect.y || y === rect.y + rect.h - 1;
      const isRamp = y === rect.y + rect.h - 1 && x === rampX; // the sole ascent, mid-south edge
      if (isRamp) {
        ground[y][x] = 'dirt';
        ramp.push([x, y]);
      } else if (edge) {
        ground[y][x] = 'cliff'; // blocked=2 — the raised edge that can't be walked off
        faces.push([x, y]);
      } else {
        ground[y][x] = 'stone_floor'; // the walkable top (GameScene grasses it over)
        plateau.push([x, y]);
      }
    }
  }
  elevationRegions.push({
    name, level, bounds: rect, plateau, faces, ramp,
    vista: { tx: rect.x + Math.floor(rect.w / 2), ty: rect.y + Math.floor(rect.h / 2) },
    vistaChunkRadius: vistaR,
  });
  return rampX;
}

// ---- Highland Crags: a TWO-TIER faux-elevation hill — you climb a ramp to the
// terrace, then a second ramp to the smaller summit (so it reads as CLIMBABLE, not
// one flat court). The lower terrace is carved first; the upper plateau is stacked
// inside it, its cliff-ring dropping onto the terrace. GameScene renders both tiers
// with per-level depth bumps + faces; the summit vista lifts the most fog.
const cragRampX = (() => {
  const lower = { x: 240, y: 24, w: 22, h: 18 };
  const upper = { x: 246, y: 25, w: 10, h: 8 }; // stacked on the terrace, toward the north
  const rampX = carveTerrace('Highland Crags', 1, lower, 6);
  // a short dirt approach from the south so the lower ramp is reachable from the ground
  for (let dy = 0; dy < 3; dy++) {
    const yy = lower.y + lower.h + dy;
    if (inBounds(rampX, yy) && ground[yy][rampX] === 'grass') ground[yy][rampX] = 'dirt';
  }
  // the upper terrace overwrites the middle of the lower plateau; drop it from the
  // lower region's plateau list so those tiles read as the SUMMIT, not the terrace
  carveTerrace('Highland Crags Summit', 2, upper, 12);
  const lowerRegion = elevationRegions[elevationRegions.length - 2];
  const upperTiles = new Set<string>();
  for (let y = upper.y; y < upper.y + upper.h; y++) for (let x = upper.x; x < upper.x + upper.w; x++) upperTiles.add(`${x},${y}`);
  lowerRegion.plateau = lowerRegion.plateau.filter(([x, y]) => !upperTiles.has(`${x},${y}`));
  return rampX;
})();

// ---- Highland Crags 3rd quarry: a stone-floor pit at the hill's foot, ringed
// with rock nodes (like the core Quarries; appended ids so core stays byte-stable)
const cragQuarry = { cx: cragRampX, cy: 54 };
fillCircle(cragQuarry.cx, cragQuarry.cy, 6, 'dirt', ['grass']);
fillCircle(cragQuarry.cx, cragQuarry.cy, 4.5, 'stone_floor', ['grass', 'dirt']);

// ---- Overgrown Temple: broken stone-floor courts among the trees
for (let i = 0; i < 14; i++) {
  fillCircle(rand(222, 280), rand(124, 184), rand(2, 5), 'stone_floor', ['grass']);
}
fillRect(240, 142, 12, 10, 'stone_floor');

// ---- Mangrove Coast: brackish water pools + swampy shallows (south frontier)
for (let i = 0; i < 32; i++) fillCircle(rand(108, 202), rand(250, 293), rand(2, 5), 'water');
for (let i = 0; i < 36; i++) fillCircle(rand(104, 204), rand(232, 292), rand(1.5, 4), 'swamp', ['grass']);

// ---- The Cavern Mouth: a rocky dirt clearing framing the (relocated) Delve shaft
fillCircle(56, 260, 8, 'dirt', ['grass', 'swamp']);
fillCircle(56, 260, 5, 'stone_floor', ['grass', 'dirt']);

// frontier connector paths (travel, not void) — never touch the core
carveFrontierPath([[202, 104], [226, 96], [248, 70], [cragRampX, 45]]); // → Highland Crags ramp
carveFrontierPath([[202, 150], [228, 150], [250, 152]]); // → Overgrown Temple
carveFrontierPath([[120, 202], [134, 228], [152, 258]]); // south road → Mangrove Coast
carveFrontierPath([[60, 202], [58, 232], [56, 258]]); // → the Cavern Mouth shaft
carveFrontierPath([[252, 96], [256, 130], [252, 150]]); // Crags ↔ Temple along the east edge

// beaches: frontier grass adjacent to the new mangrove water becomes sand
// (bounded to the pinned pre-Realm map — district space is generated below)
for (let y = CORE_H; y < PREV_H; y++) {
  for (let x = 0; x < PREV_W; x++) {
    if (ground[y][x] !== 'grass') continue;
    for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]] as [number, number][]) {
      if (inBounds(x + dx, y + dy) && ground[y + dy][x + dx] === 'water') { ground[y][x] = 'sand'; break; }
    }
  }
}

// ---- frontier ambient nodes: same density logic, appended ids (core untouched).
// BOUNDED TO THE PINNED 300×300 MAP: the exact same iteration + RNG sequence as
// before the Realm growth, so every frontier node id stays byte-stable too
// (district nodes are authored below, RNG-free, ids appended after these).
for (let gy = 1; gy < PREV_H - 1; gy += 2) {
  for (let gx = 1; gx < PREV_W - 1; gx += 2) {
    if (gx < CORE_W && gy < CORE_H) continue; // the core was generated above
    const x = gx + Math.floor(rand(0, 2));
    const y = gy + Math.floor(rand(0, 2));
    if (!inBounds(x, y)) continue;
    const zone = zoneAt(x, y);
    const roll = rng();
    const tree = treeDensity[zone] ?? 0.12;
    const bush = bushDensity[zone] ?? 0.02;
    const vine = vineDensity[zone] ?? 0.008;
    if (roll < tree) tryPlaceNode('tree', x, y);
    else if (roll < tree + bush) tryPlaceNode('fruit_bush', x, y);
    else if (roll < tree + bush + vine) tryPlaceNode('fiber_vine', x, y);
  }
}

// ---- frontier payoff nodes (deterministic placements → stable appended ids)
// Highland Crags quarry ring
for (const [dx, dy] of [
  [-4, -1], [-3, -3], [-1, -4], [2, -4], [4, -2], [4, 1], [3, 3], [0, 4], [-3, 3], [-1, 0], [1, -1], [2, 2],
] as [number, number][]) {
  tryPlaceNode('rock', cragQuarry.cx + dx, cragQuarry.cy + dy);
}
// Overgrown Temple tier-2 grove: obsidian + ancient hardwood
for (const [x, y] of [[230, 140], [244, 134], [256, 148], [238, 164], [262, 158], [226, 152]] as [number, number][]) {
  placeNodeNear('obsidian_rock', x, y);
}
for (const [x, y] of [[248, 128], [234, 150], [258, 138], [242, 172], [224, 166], [266, 150]] as [number, number][]) {
  placeNodeNear('hardwood_tree', x, y);
}
// Mangrove Coast fishing spots
for (const [x, y] of [[130, 258], [150, 266], [168, 252], [186, 270], [120, 278], [176, 286]] as [number, number][]) {
  placeFishingSpotNear(x, y);
}
// The Cavern Mouth obsidian veins by the shaft
for (const [x, y] of [[44, 252], [72, 266], [80, 248], [38, 274]] as [number, number][]) {
  placeNodeNear('obsidian_rock', x, y);
}

// ============================================================ REALM DISTRICTS (ADR-0017 §2)
// A Realm reads as its own small map but is a rectangular district appended in
// the unused grid space beyond the pinned 300×300 World — gate teleport is the
// ONLY way in (no walkable connection; camera/minimap clamp sell the illusion).
// Everything here is APPENDED: node ids continue the one sequence (placement is
// RNG-free), and all terrain randomness uses the separate rng2 stream, so the
// pinned map's draws — terrain, nodes, decor, tile variants — never shift.

interface DistrictOut {
  id: string;
  /** English display name — the HUD localizes it like a zone name (ZONE_DE) */
  name: string;
  rect: { x: number; y: number; w: number; h: number };
  /** the paired teleport gates: the world-side arch and its district-side twin */
  gate: { worldTx: number; worldTy: number; districtTx: number; districtTy: number };
}
const districts: DistrictOut[] = [];

// the Hushdark's pedestal-vaults (ADR-0017 rung 2): each vault opens only while
// every one of its pedestal tiles is covered at once by an overlaid echo/player
// (async co-op); `door` is where the opened cache is claimed. GameScene + backend
// derive open/claim from these — the tiles are walkable plinths, never blockers.
const hushdarkVaults: { id: string; pedestals: { tx: number; ty: number }[]; door: { tx: number; ty: number } }[] = [];
// the memorial plinth: where a Player who has defeated the Reverberant leaves a
// permanent, named greeting shade for others (ADR-0017 rung 2, the async-coop mark)
let hushdarkMemorial: { tx: number; ty: number } | null = null;
// the Reverberant's arena (ADR-0017 rung 2): the 3-pedestal puzzle court IS the
// boss court — a full ARENA_W×ARENA_H so the wave grid lines up. No cliff walls /
// no Ward (open court); the boss rises here when the puzzle is solved.
const REVERB_ARENA = { x: 32, y: 334, w: ARENA_W, h: ARENA_H }; // contains all 3 pedestals
const REVERB_HOME = { tx: REVERB_ARENA.x + Math.floor(ARENA_W / 2) - 1, ty: REVERB_ARENA.y + 1 };

// void filler: every appended tile starts as unwalkable cliff — cheap to
// render, impossible to walk, and the moat that seals district space off from
// the World's open south/east edges. District interiors are carved out below.
for (let y = 0; y < H; y++) {
  for (let x = 0; x < W; x++) {
    if (x < PREV_W && y < PREV_H) continue;
    ground[y][x] = 'cliff';
  }
}

/** deterministic spiral for a clear world-side gate spot near (cx,cy): solid
 *  walkable ground on the gate tile AND the tile south of it (the returning
 *  Player appears there), nothing already standing on either. No RNG and no
 *  terrain writes — the pinned map is never edited to host a gate. */
function findGateSpot(cx: number, cy: number, maxR = 10): { tx: number; ty: number } {
  const okGround = (x: number, y: number) => {
    const g = inBounds(x, y) ? ground[y][x] : null;
    return g === 'grass' || g === 'dirt' || g === 'sand' || g === 'swamp' || g === 'stone_floor';
  };
  for (let r = 0; r <= maxR; r++) {
    for (let dy = -r; dy <= r; dy++) {
      for (let dx = -r; dx <= r; dx++) {
        if (Math.max(Math.abs(dx), Math.abs(dy)) !== r) continue;
        const x = cx + dx;
        const y = cy + dy;
        if (!okGround(x, y) || !okGround(x, y + 1)) continue;
        if (occupied.has(`${x},${y}`) || occupied.has(`${x},${y + 1}`)) continue;
        return { tx: x, ty: y };
      }
    }
  }
  throw new Error(`no clear Realm-gate spot near ${cx},${cy}`);
}

// ---- rung 1: The Sunken Mire, south of the Mangrove Coast. A drowned peat
// bog: near-black channels wind through dark peat, wet mud banks carry pale
// reeds, an old flagstone causeway sinks southward from the gate to a ruined
// islet (where T5's Brine Kiln and the Tide will live). Dead trees watch.
{
  const rect = { x: 100, y: 300, w: 108, h: 72 }; // keep in sync with its Zone rect above
  // interior: the rect keeps a 1-tile cliff ring of its own (the void already
  // provides one, but the ring survives any future neighbouring district)
  fillRect(rect.x + 1, rect.y + 1, rect.w - 2, rect.h - 2, 'mire_peat');

  // the drowned heart — a broad lake off-center…
  fillCircle(154, 339, 11, 'mire_water', ['mire_peat']);
  fillCircle(146, 331, 8, 'mire_water', ['mire_peat']);
  fillCircle(164, 346, 8, 'mire_water', ['mire_peat']);
  // …with winding channels wandering off it (chained blobs, rng2 stream)
  let cx = 143;
  let cy = 332;
  for (let i = 0; i < 15; i++) {
    cx -= rand2(1.5, 3.5);
    cy += rand2(-2.5, 2);
    fillCircle(cx, cy, rand2(1.8, 3.2), 'mire_water', ['mire_peat']);
  }
  cx = 165;
  cy = 347;
  for (let i = 0; i < 15; i++) {
    cx += rand2(1.5, 3.5);
    cy += rand2(-1.5, 2.5);
    fillCircle(cx, cy, rand2(1.8, 3.2), 'mire_water', ['mire_peat']);
  }
  cx = 161;
  cy = 333;
  for (let i = 0; i < 11; i++) {
    cx += rand2(1, 3);
    cy -= rand2(1, 2.5);
    fillCircle(cx, cy, rand2(1.5, 2.6), 'mire_water', ['mire_peat']);
  }
  // scattered black pools
  for (let i = 0; i < 18; i++) {
    fillCircle(rand2(rect.x + 8, rect.x + rect.w - 8), rand2(rect.y + 10, rect.y + rect.h - 8), rand2(1.2, 3), 'mire_water', ['mire_peat']);
  }

  // the gate landing — an old paved threshold, always dry (painted after the
  // pools so the arch approach can never flood)
  const dGate = { tx: 153, ty: 303 };
  fillRect(dGate.tx - 3, dGate.ty - 1, 7, 5, 'mire_peat');
  fillRect(dGate.tx - 2, dGate.ty, 5, 3, 'mire_flagstone');

  // wet mud banks: every peat tile touching black water becomes shore
  for (let y = rect.y + 1; y < rect.y + rect.h - 1; y++) {
    for (let x = rect.x + 1; x < rect.x + rect.w - 1; x++) {
      if (ground[y][x] !== 'mire_peat') continue;
      if (
        ground[y - 1][x] === 'mire_water' ||
        ground[y + 1][x] === 'mire_water' ||
        ground[y][x - 1] === 'mire_water' ||
        ground[y][x + 1] === 'mire_water'
      ) {
        ground[y][x] = 'mire_mud';
      }
    }
  }

  // the ruined islet at the lake's heart — T5's altar/Brine Kiln ground
  // (all drowned flagstone: clean World stone would glare against the murk)
  fillCircle(154, 339, 3.6, 'mire_flagstone', ['mire_water', 'mire_mud', 'mire_peat']);
  foliage.push({ kind: 'ruin_pillar', tx: 152, ty: 337 });
  foliage.push({ kind: 'ruin_pillar', tx: 156, ty: 341 });
  occupied.add('152,337');
  occupied.add('156,341');

  // the drowned causeway: gate landing → islet, two slabs wide, wandering but
  // bending home toward the islet. The bog may swallow ONE slab of a row —
  // and only when the path isn't drifting sideways, never two rows running,
  // with the next row holding its line — so the surviving slabs always stack
  // 4-adjacent and the islet (which has no other dry approach) stays walkable.
  let px = 153.5;
  let prevGx = 153;
  let lastGap: boolean = false;
  for (let py = dGate.ty + 3; py <= 336; py++) {
    px += rand2(-0.5, 0.5) + (154 - px) * 0.12;
    let gx = Math.round(px);
    if (lastGap) {
      gx = prevGx; // hold the line right after a swallowed slab
      px = prevGx;
    }
    const roll = rng2();
    const gap: boolean = py <= 333 && !lastGap && gx === prevGx && roll < 0.22;
    const dropDx = roll < 0.11 ? -1 : 0;
    for (let dx = -1; dx <= 0; dx++) {
      if (gap && dx === dropDx) continue;
      if (inBounds(gx + dx, py)) ground[py][gx + dx] = 'mire_flagstone';
    }
    lastGap = gap;
    prevGx = gx;
  }

  // reeds and cattails crowd the banks; lily pads drift on the still water
  for (let y = rect.y + 1; y < rect.y + rect.h - 1; y++) {
    for (let x = rect.x + 1; x < rect.x + rect.w - 1; x++) {
      const g = ground[y][x];
      if (g === 'mire_mud' && rng2() < 0.34) decor[y][x] = rng2() < 0.7 ? 'reeds' : 'cattails';
      else if (g === 'mire_peat' && rng2() < 0.035) decor[y][x] = 'reeds';
      else if (g === 'mire_water' && rng2() < 0.05) decor[y][x] = 'lilypad';
    }
  }

  // dead bog trees — gnarled silhouettes on open peat, never crowding the
  // causeway's line of sight from the gate
  let planted = 0;
  for (let i = 0; i < 40 && planted < 14; i++) {
    const tx = Math.round(rand2(rect.x + 5, rect.x + rect.w - 6));
    const ty = Math.round(rand2(rect.y + 6, rect.y + rect.h - 6));
    if (ground[ty][tx] !== 'mire_peat' || decor[ty][tx] || occupied.has(`${tx},${ty}`)) continue;
    if (Math.abs(tx - dGate.tx) < 4 && ty < 315) continue;
    foliage.push({ kind: 'dead_tree', tx, ty });
    occupied.add(`${tx},${ty}`);
    planted++;
  }

  // the Mire's OWN Resource: salt-reed beds crowd the banks around the lake
  // and channels (ADR-0017 rung 1 chain — T5's Brine Kiln refines the reeds).
  // Bare-handed harvest; the Tide will gate their exposure once T5 lands.
  for (const [x, y] of [
    [148, 328], [160, 330], [146, 344], [162, 350], [152, 346], [140, 334], [168, 342],
    [132, 326], [172, 330], [120, 340], [184, 352], [156, 324], [136, 352], [176, 346],
  ] as [number, number][]) {
    placeNodeNear('salt_reed_bed', x, y);
  }
  // fiber vines as the familiar secondary pull; no jungle trees in here —
  // lush canopy would break the drowned-bog read (bogwood snags come with T5)
  for (const [x, y] of [[120, 316], [138, 340], [168, 322], [186, 350], [150, 358], [112, 344], [128, 330], [176, 336]] as [number, number][]) {
    placeNodeNear('fiber_vine', x, y);
  }
  placeFishingSpotNear(148, 336);
  const worldGate = findGateSpot(152, 290); // Mangrove Coast, by the south road's end
  districts.push({
    id: 'sunken_mire',
    name: 'The Sunken Mire',
    rect,
    gate: { worldTx: worldGate.tx, worldTy: worldGate.ty, districtTx: dGate.tx, districtTy: dGate.ty },
  });
}

// ---- rung 2: The Hushdark, south of The Cavern Mouth. A cold stone cavern of
// grey floor ringed in cliff, with near-black ink pools and a cluster of ritual
// pedestals around a sealed vault. Built ONLY from existing tiles and its OWN
// third RNG stream (rng3) with NO decor, so neither the pinned map nor the
// already-shipped Sunken Mire district shifts by a byte. The Hushdark's identity
// is carried scene-side by a cold, muffled ambience veil + its Zone name.
{
  const rect = { x: 16, y: 300, w: 80, h: 72 }; // keep in sync with its Zone rect above
  // interior: a grey cavern floor with a 1-tile cliff ring (the void supplies it)
  fillRect(rect.x + 1, rect.y + 1, rect.w - 2, rect.h - 2, 'stone_floor');

  // near-black ink pools scattered through the cavern (rng3 stream, no decor)
  fillCircle(34, 356, 6, 'mire_water', ['stone_floor']);
  fillCircle(74, 348, 7, 'mire_water', ['stone_floor']);
  fillCircle(60, 362, 5, 'mire_water', ['stone_floor']);
  for (let i = 0; i < 14; i++) {
    fillCircle(rand3(rect.x + 6, rect.x + rect.w - 6), rand3(rect.y + 12, rect.y + rect.h - 6), rand3(1.1, 2.6), 'mire_water', ['stone_floor']);
  }
  // stalagmite clumps — small cliff outcrops that break the floor's line of sight
  for (let i = 0; i < 10; i++) {
    fillCircle(rand3(rect.x + 5, rect.x + rect.w - 5), rand3(rect.y + 8, rect.y + rect.h - 5), rand3(0.8, 1.6), 'cliff', ['stone_floor']);
  }

  // the gate landing — a dry paved threshold near the Cavern Mouth's south edge
  const dGate = { tx: 56, ty: 303 };
  fillRect(dGate.tx - 3, dGate.ty - 1, 7, 5, 'stone_floor');
  fillRect(dGate.tx - 2, dGate.ty, 5, 3, 'sand');

  // the pedestal court (ADR-0017 rung 2): three ritual pedestals spaced too far
  // for one shade to hold together. Solving the puzzle (a shade on each of the
  // three at once) SUMMONS the Reverberant, which rises HERE — so the court is
  // sized to the boss arena (REVERB_ARENA, ARENA_W×ARENA_H, open, no cliff walls).
  const door = { tx: 40, ty: 340 };
  const pedestals = [
    { tx: 34, ty: 337 },
    { tx: 46, ty: 337 },
    { tx: 40, ty: 346 },
  ];
  fillRect(REVERB_ARENA.x, REVERB_ARENA.y, REVERB_ARENA.w, REVERB_ARENA.h, 'stone_floor'); // clear the court of pools
  for (const ped of pedestals) {
    ground[ped.ty][ped.tx] = 'sand'; // a pale plinth
    occupied.add(`${ped.tx},${ped.ty}`); // no crystal node ever spawns on a plinth
  }
  ground[door.ty][door.tx] = 'sand';
  occupied.add(`${door.tx},${door.ty}`);
  hushdarkVaults.push({ id: 'hush_vault_1', pedestals, door });

  // the memorial plinth: a lone pillar just south of the court where a Player who
  // has defeated the Reverberant leaves their permanent, named greeting shade
  hushdarkMemorial = { tx: 40, ty: 350 };
  fillRect(hushdarkMemorial.tx - 2, hushdarkMemorial.ty - 4, 5, 6, 'stone_floor'); // bridge court→memorial, keep reachable
  ground[hushdarkMemorial.ty][hushdarkMemorial.tx] = 'sand';
  occupied.add(`${hushdarkMemorial.tx},${hushdarkMemorial.ty}`);
  foliage.push({ kind: 'ruin_pillar', tx: hushdarkMemorial.tx, ty: hushdarkMemorial.ty - 1 });
  occupied.add(`${hushdarkMemorial.tx},${hushdarkMemorial.ty - 1}`);

  // the Hushdark's OWN Resource: echo-crystal seams on the open cavern floor
  // (ADR-0017 rung 2 chain — the Chime Kiln rings them into hushsteel)
  for (const [x, y] of [
    [26, 314], [70, 316], [30, 328], [80, 330], [22, 348], [84, 358], [50, 320],
    [66, 332], [38, 360], [78, 366], [28, 366], [86, 344],
  ] as [number, number][]) {
    placeNodeNear('echo_crystal_seam', x, y);
  }
  // rock outcrops as the secondary pull — stone, mined from the cavern floor (a
  // bare cave has no vines; rock is accepted on stone_floor, unlike fiber_vine)
  for (const [x, y] of [[24, 320], [82, 322], [46, 360], [72, 358], [34, 350], [60, 314]] as [number, number][]) {
    placeNodeNear('rock', x, y);
  }
  const worldGate = findGateSpot(50, 292); // Cavern Mouth, near its south edge, clear of the Delve
  districts.push({
    id: 'the_hushdark',
    name: 'The Hushdark',
    rect,
    gate: { worldTx: worldGate.tx, worldTy: worldGate.ty, districtTx: dGate.tx, districtTy: dGate.ty },
  });
}

// ---- rung 3: The Green Terraces, appended east of the Sunken Mire in the far
// south. Marsh-terraced hillside paddies of wildgrain: a swamp-green field stepped
// by dry earthen embankments, fresh irrigation channels winding between them, a
// paved gate landing at the north edge. Built ONLY from existing tiles and its OWN
// fourth RNG stream (rng4), with NO decor and NO grass, so neither the pinned map
// nor the already-shipped Mire/Hushdark districts shifts by a byte (each tile still
// costs exactly one shared pick2, same as the void cliff it replaces). Its green
// identity is carried scene-side by the ambience veil + the Zone name.
{
  const rect = { x: 220, y: 300, w: 120, h: 72 }; // keep in sync with its Zone rect above
  // interior: a marsh-field base with a 1-tile cliff ring (the void supplies it)
  fillRect(rect.x + 1, rect.y + 1, rect.w - 2, rect.h - 2, 'swamp');

  // stepped terraces: dry earthen embankment walls band the hillside east–west,
  // reading as the retaining steps between the flooded paddies (RNG-free)
  for (const by of [316, 330, 344, 358]) {
    fillRect(rect.x + 3, by, rect.w - 6, 2, 'mire_peat');
  }

  // the gate landing — a dry paved threshold at the north edge, painted before the
  // channels so the arch approach can never flood
  const dGate = { tx: 280, ty: 303 };
  fillRect(dGate.tx - 3, dGate.ty - 1, 7, 5, 'mire_peat');
  fillRect(dGate.tx - 2, dGate.ty, 5, 3, 'sand');

  // fresh irrigation channels winding along the paddy steps (rng4 stream only),
  // kept to the central and southern field so the northern grove stays dry. The
  // `over:['swamp']` guard means water never cuts the dry embankments or landing.
  let cx = 236;
  let cy = 322;
  for (let i = 0; i < 16; i++) {
    cx += rand4(1.6, 3.4);
    cy += rand4(-1.5, 2.2);
    fillCircle(cx, cy, rand4(1.3, 2.4), 'water', ['swamp']);
  }
  cx = 322;
  cy = 338;
  for (let i = 0; i < 16; i++) {
    cx -= rand4(1.6, 3.4);
    cy += rand4(-2, 1.8);
    fillCircle(cx, cy, rand4(1.3, 2.4), 'water', ['swamp']);
  }
  // still ponds scattered across the lower fields
  for (let i = 0; i < 12; i++) {
    fillCircle(rand4(rect.x + 10, rect.x + rect.w - 10), rand4(340, rect.y + rect.h - 8), rand4(1.1, 2.2), 'water', ['swamp']);
  }

  // the Green Terraces' OWN Resource: wildgrain beds crowd the marsh paddies
  // between the embankments (ADR-0017 rung 3 chain — the Verdant Loom rets them
  // into verdant fibre; Cultivation gates their ripe window client-side). Placed
  // RNG-FREE after the Hushdark's nodes, so every pre-existing node id is stable.
  for (const [x, y] of [
    [228, 320], [246, 324], [266, 322], [288, 326], [308, 320], [328, 324],
    [236, 338], [258, 340], [282, 336], [304, 342], [326, 338],
    [248, 352], [274, 354], [300, 350], [322, 356], [290, 366],
  ] as [number, number][]) {
    placeNodeNear('wildgrain_bed', x, y);
  }
  // a hedgerow grove on the dry northern band for wood, and terrace boulders for
  // stone — the familiar secondary pulls, both accepted off-grass (tree on swamp
  // clear of the channels; rock on the mire_peat embankments)
  for (const [x, y] of [[230, 308], [252, 310], [276, 308], [300, 309], [324, 311]] as [number, number][]) {
    placeNodeNear('tree', x, y);
  }
  for (const [x, y] of [[240, 316], [286, 330], [312, 344], [258, 358]] as [number, number][]) {
    placeNodeNear('rock', x, y);
  }

  const worldGate = findGateSpot(277, 292); // SE frontier, just north of the district
  districts.push({
    id: 'green_terraces',
    name: 'The Green Terraces',
    rect,
    gate: { worldTx: worldGate.tx, worldTy: worldGate.ty, districtTx: dGate.tx, districtTy: dGate.ty },
  });
}

// decor: flowers and small plants on open grass. Loop 1 is the pinned 300×300
// map in its exact old row-major order (same main-stream RNG draws); loop 2 is
// the appended district space, drawing from the district stream.
for (let y = 0; y < PREV_H; y++) {
  for (let x = 0; x < PREV_W; x++) {
    if (ground[y][x] === 'grass' && !occupied.has(`${x},${y}`) && rng() < 0.035) {
      decor[y][x] = rng() < 0.5 ? 'flower' : 'plant';
    }
  }
}
for (let y = 0; y < H; y++) {
  for (let x = 0; x < W; x++) {
    if (x < PREV_W && y < PREV_H) continue; // pinned above
    if (ground[y][x] === 'grass' && !occupied.has(`${x},${y}`) && rng2() < 0.035) {
      decor[y][x] = rng2() < 0.5 ? 'flower' : 'plant';
    }
  }
}

// ---- ADR-0017 rung 1: carve the Mire Warden's arena into the Mangrove Coast.
// LATE + RNG-FREE (after every node + decor draw) so nothing shifts: a cliff wall
// ring, a drowned-flagstone floor, the south Ward gap. Ground writes only — the
// footprint's decor is discarded from decorGid below the tile-variant picks (the
// picks are still made, count preserved), and footprint nodes are evicted by id.
for (let y = MIRE_ARENA.y - 1; y <= MIRE_ARENA.y + MIRE_ARENA.h; y++) {
  for (let x = MIRE_ARENA.x - 1; x <= MIRE_ARENA.x + MIRE_ARENA.w; x++) {
    if (!inBounds(x, y)) continue;
    const isWall = x === MIRE_ARENA.x - 1 || x === MIRE_ARENA.x + MIRE_ARENA.w || y === MIRE_ARENA.y - 1 || y === MIRE_ARENA.y + MIRE_ARENA.h;
    ground[y][x] = isWall ? 'cliff' : 'mire_flagstone';
  }
}
for (const g of MIRE_SEAL_GATE) ground[g.ty][g.tx] = 'mire_flagstone'; // the entrance gap the Ward blocks
// the offering monument stands on dry ground just outside the south gate
for (const m of [MIRE_MONUMENT, { tx: MIRE_MONUMENT.tx + 1, ty: MIRE_MONUMENT.ty }]) {
  const g = ground[m.ty][m.tx];
  if (g === 'water' || g === 'mire_water' || g === 'cliff') ground[m.ty][m.tx] = 'sand';
}

// ---- ADR-0017 rung 2: carve the Echo Warden's arena into The Cavern Mouth, the
// same LATE + RNG-FREE discipline as the Mire arena: a cliff wall ring, a stone
// floor court, the south Ward gap. Ground writes only — footprint decor is dropped
// from decorGid below the tile-variant picks (picks still made, count preserved),
// and footprint nodes are evicted by id via keptNodes.
for (let y = ECHO_ARENA.y - 1; y <= ECHO_ARENA.y + ECHO_ARENA.h; y++) {
  for (let x = ECHO_ARENA.x - 1; x <= ECHO_ARENA.x + ECHO_ARENA.w; x++) {
    if (!inBounds(x, y)) continue;
    const isWall = x === ECHO_ARENA.x - 1 || x === ECHO_ARENA.x + ECHO_ARENA.w || y === ECHO_ARENA.y - 1 || y === ECHO_ARENA.y + ECHO_ARENA.h;
    ground[y][x] = isWall ? 'cliff' : 'stone_floor';
  }
}
for (const g of ECHO_SEAL_GATE) ground[g.ty][g.tx] = 'stone_floor'; // the entrance gap the Ward blocks
for (const m of [ECHO_MONUMENT, { tx: ECHO_MONUMENT.tx + 1, ty: ECHO_MONUMENT.ty }]) {
  const g = ground[m.ty][m.tx];
  if (g === 'water' || g === 'mire_water' || g === 'cliff') ground[m.ty][m.tx] = 'sand';
}

// ---- ADR-0017 rung 3: carve the Verdant Warden's arena into the SE frontier, the
// same LATE + RNG-FREE discipline as the Mire and Echo arenas: a cliff wall ring, a
// stone floor court, the south Ward gap. Ground writes only — footprint decor is
// dropped from decorGid below the tile-variant picks (picks still made, count
// preserved), and footprint nodes are evicted by id via keptNodes.
for (let y = VERDANT_ARENA.y - 1; y <= VERDANT_ARENA.y + VERDANT_ARENA.h; y++) {
  for (let x = VERDANT_ARENA.x - 1; x <= VERDANT_ARENA.x + VERDANT_ARENA.w; x++) {
    if (!inBounds(x, y)) continue;
    const isWall = x === VERDANT_ARENA.x - 1 || x === VERDANT_ARENA.x + VERDANT_ARENA.w || y === VERDANT_ARENA.y - 1 || y === VERDANT_ARENA.y + VERDANT_ARENA.h;
    ground[y][x] = isWall ? 'cliff' : 'stone_floor';
  }
}
for (const g of VERDANT_SEAL_GATE) ground[g.ty][g.tx] = 'stone_floor'; // the entrance gap the Ward blocks
for (const m of [VERDANT_MONUMENT, { tx: VERDANT_MONUMENT.tx + 1, ty: VERDANT_MONUMENT.ty }]) {
  const g = ground[m.ty][m.tx];
  if (g === 'water' || g === 'mire_water' || g === 'cliff') ground[m.ty][m.tx] = 'sand';
}

// ---------------------------------------------------------------- secrets
// Placed AFTER node generation on purpose: nodes standing on these tiles are
// evicted (already-assigned node ids stay stable for existing saves).
const tablets = [
  { id: 't0', tx: 160, ty: 36 }, // ruins center
  { id: 't1', tx: 149, ty: 25 }, // ruins north
  { id: 't2', tx: 93, ty: 39 }, // falls shore
  { id: 't3', tx: 45, ty: 158 }, // river delta
  { id: 't4', tx: 152, ty: 162 }, // swamp edge
  { id: 't5', tx: 166, ty: 32 }, // v2: Tablet of the Seal, on the arena approach
  { id: 't6', tx: 246, ty: 147 }, // frontier: Overgrown Temple court (ADR-0009)
  { id: 't7', tx: 155, ty: 304 }, // ADR-0017 rung 1: Tablet of the Tide, on the Sunken Mire's gate landing
  { id: 't8', tx: 48, ty: 306 }, // ADR-0017 rung 2: Tablet of the Hushdark, inside the Hushdark district
  { id: 't9', tx: 38, ty: 350 }, // ADR-0017 rung 2: by the memorial, south of the Reverberant's court
  { id: 't10', tx: 270, ty: 306 }, // ADR-0017 rung 3: Tablet of the Season, on the Green Terraces' north band
];
const altar = { tx: 35, ty: 75 }; // watches the hidden grove entrance
const gate = [73, 74, 75, 76, 77].map((y) => ({ tx: 32, ty: y }));
const treasureSpots = [
  { tx: 44, ty: 162 }, // delta sands
  { tx: 92, ty: 13 }, // beneath the northern cliffs
  { tx: 168, ty: 48 }, // ruins
  { tx: 148, ty: 172 }, // swamp
  { tx: 20, ty: 75 }, // heart of the hidden grove
  { tx: 64, ty: 58 }, // deep jungle west
  { tx: 158, ty: 274 }, // frontier: Mangrove Coast shipwreck (ADR-0009)
  { tx: 50, ty: 256 }, // frontier: beside the Cavern Mouth
];
// v2 landmarks
const sealMonument = { tx: 173, ty: 31 }; // 2 tiles wide, watches the arena entrance
const guardianAltar = { tx: ARENA.x + 7, ty: ARENA.y + 10 }; // 2 tiles, inside the arena near the gate
const welcomeStone = { tx: 98, ty: 97 }; // beside spawn — re-read the intro here
const reservedTiles = new Set(
  [
    ...tablets,
    altar,
    { tx: altar.tx + 1, ty: altar.ty },
    ...gate,
    ...treasureSpots,
    sealMonument,
    { tx: sealMonument.tx + 1, ty: sealMonument.ty },
    guardianAltar,
    { tx: guardianAltar.tx + 1, ty: guardianAltar.ty },
    welcomeStone,
    ...SEAL_GATE,
  ].map((s) => `${s.tx},${s.ty}`),
);
for (const key of reservedTiles) {
  const [x, y] = key.split(',').map(Number);
  const g = ground[y][x];
  if (g === 'water' || g === 'cliff') ground[y][x] = 'grass';
  decor[y][x] = null;
}
const keptNodes = nodes.filter(
  (n) =>
    !reservedTiles.has(`${n.tx},${n.ty}`) &&
    !inArenaOuter(n.tx, n.ty) &&
    !inMireArenaOuter(n.tx, n.ty) &&
    !isMireMonument(n.tx, n.ty) &&
    !inEchoArenaOuter(n.tx, n.ty) &&
    !isEchoMonument(n.tx, n.ty) &&
    !inVerdantArenaOuter(n.tx, n.ty) &&
    !isVerdantMonument(n.tx, n.ty),
);

// ---------------------------------------------------------------- outputs
const blocked = new Array<number>(W * H).fill(0);
for (let y = 0; y < H; y++) {
  for (let x = 0; x < W; x++) {
    const g = ground[y][x];
    blocked[y * W + x] = g === 'water' || g === 'mire_water' ? 1 : g === 'cliff' ? 2 : 0;
  }
}
// the Guardian's 3x3 resting place is solid — it is always physically there
for (let dy = 0; dy < 3; dy++) {
  for (let dx = 0; dx < 3; dx++) {
    blocked[(GUARDIAN_HOME.ty + dy) * W + (GUARDIAN_HOME.tx + dx)] = 2;
  }
}
// the Mire Warden's 3x3 resting place, likewise solid (ADR-0017 rung 1)
for (let dy = 0; dy < 3; dy++) {
  for (let dx = 0; dx < 3; dx++) {
    blocked[(MIRE_HOME.ty + dy) * W + (MIRE_HOME.tx + dx)] = 2;
  }
}
// the Echo Warden's 3x3 resting place, likewise solid (ADR-0017 rung 2)
for (let dy = 0; dy < 3; dy++) {
  for (let dx = 0; dx < 3; dx++) {
    blocked[(ECHO_HOME.ty + dy) * W + (ECHO_HOME.tx + dx)] = 2;
  }
}
// the Verdant Warden's 3x3 resting place, likewise solid (ADR-0017 rung 3)
for (let dy = 0; dy < 3; dy++) {
  for (let dx = 0; dx < 3; dx++) {
    blocked[(VERDANT_HOME.ty + dy) * W + (VERDANT_HOME.tx + dx)] = 2;
  }
}

// tile-variant picks: the pinned 300×300 map draws FIRST, in its exact old
// row-major order from the main stream (identical variants at every
// pre-existing tile); the appended district space draws from the district
// stream. The flat Tiled arrays are then assembled row-major over the full grid.
const groundGid: number[][] = Array.from({ length: H }, () => Array<number>(W).fill(0));
const decorGid: number[][] = Array.from({ length: H }, () => Array<number>(W).fill(0));
const pickTile = (x: number, y: number, p: <U>(arr: U[]) => U) => {
  groundGid[y][x] = p(T[ground[y][x]]) + 1;
  const d = decor[y][x];
  decorGid[y][x] = d ? p(T[d]) + 1 : 0;
};
for (let y = 0; y < PREV_H; y++) {
  for (let x = 0; x < PREV_W; x++) pickTile(x, y, pick);
}
for (let y = 0; y < H; y++) {
  for (let x = 0; x < W; x++) {
    if (x < PREV_W && y < PREV_H) continue; // pinned above
    pickTile(x, y, pick2);
  }
}
// ADR-0017 rung 1: discard any decor the pick loop drew onto the Mire arena
// footprint (the picks were still MADE — stream count preserved — only their gid
// is dropped, so no pinned tile-variant ever shifts) so no flowers sprout on the
// drowned-flagstone court or its cliff walls.
for (let y = MIRE_ARENA.y - 1; y <= MIRE_ARENA.y + MIRE_ARENA.h; y++) {
  for (let x = MIRE_ARENA.x - 1; x <= MIRE_ARENA.x + MIRE_ARENA.w; x++) {
    if (inBounds(x, y)) decorGid[y][x] = 0;
  }
}
// ADR-0017 rung 2: same discard for the Echo arena footprint
for (let y = ECHO_ARENA.y - 1; y <= ECHO_ARENA.y + ECHO_ARENA.h; y++) {
  for (let x = ECHO_ARENA.x - 1; x <= ECHO_ARENA.x + ECHO_ARENA.w; x++) {
    if (inBounds(x, y)) decorGid[y][x] = 0;
  }
}
// ADR-0017 rung 3: same discard for the Verdant arena footprint
for (let y = VERDANT_ARENA.y - 1; y <= VERDANT_ARENA.y + VERDANT_ARENA.h; y++) {
  for (let x = VERDANT_ARENA.x - 1; x <= VERDANT_ARENA.x + VERDANT_ARENA.w; x++) {
    if (inBounds(x, y)) decorGid[y][x] = 0;
  }
}

const groundData: number[] = [];
const decorData: number[] = [];
for (let y = 0; y < H; y++) {
  for (let x = 0; x < W; x++) {
    groundData.push(groundGid[y][x]);
    decorData.push(decorGid[y][x]);
  }
}

const collide = [...new Set([...T.water, ...T.cliff, ...T.mire_water])].map((i) => i + 1);

const tiledMap = {
  type: 'map',
  version: '1.10',
  tiledversion: '1.10.2',
  orientation: 'orthogonal',
  renderorder: 'right-down',
  infinite: false,
  width: W,
  height: H,
  tilewidth: TILESET.tileSize,
  tileheight: TILESET.tileSize,
  nextlayerid: 3,
  nextobjectid: 1,
  layers: [
    { type: 'tilelayer', id: 1, name: 'ground', width: W, height: H, x: 0, y: 0, opacity: 1, visible: true, data: groundData },
    { type: 'tilelayer', id: 2, name: 'decor', width: W, height: H, x: 0, y: 0, opacity: 1, visible: true, data: decorData },
  ],
  tilesets: [
    {
      firstgid: 1,
      name: TILESET.name,
      tilewidth: TILESET.tileSize,
      tileheight: TILESET.tileSize,
      spacing: 0,
      margin: 0,
      columns: TILESET.columns,
      tilecount: (TILESET.imagewidth / TILESET.tileSize) * (TILESET.imageheight / TILESET.tileSize),
      image: TILESET.image,
      imagewidth: TILESET.imagewidth,
      imageheight: TILESET.imageheight,
    },
  ],
};

const worldData = {
  spawn: SPAWN,
  zones,
  nodes: keptNodes,
  foliage,
  blocked,
  collide,
  tablets,
  gate,
  altar,
  treasureSpots,
  arena: ARENA,
  guardianHome: GUARDIAN_HOME,
  sealMonument,
  guardianAltar,
  sealGate: SEAL_GATE,
  welcomeStone,
  // faux-elevation regions (ADR-0009): GameScene draws the shadow/faces + depth bump
  elevation: { regions: elevationRegions },
  // Realm districts (ADR-0017 §2): far-edge rects + their paired teleport gates
  districts,
  // ADR-0017 §1: per-Warden arenas in the World (rung 0's Guardian keeps the
  // top-level arena/guardianHome/guardianAltar/sealMonument fields). Each entry
  // mirrors that anatomy — court rect, colossus home, summoning altar, offering
  // monument, Ward gap — keyed by WardenDef id so both backends pick by fight.warden.
  wardenArenas: {
    mire: {
      arena: MIRE_ARENA,
      home: MIRE_HOME,
      altar: MIRE_ALTAR,
      monument: MIRE_MONUMENT,
      sealGate: MIRE_SEAL_GATE,
    },
    echo: {
      arena: ECHO_ARENA,
      home: ECHO_HOME,
      altar: ECHO_ALTAR,
      monument: ECHO_MONUMENT,
      sealGate: ECHO_SEAL_GATE,
    },
    verdant: {
      arena: VERDANT_ARENA,
      home: VERDANT_HOME,
      altar: VERDANT_ALTAR,
      monument: VERDANT_MONUMENT,
      sealGate: VERDANT_SEAL_GATE,
    },
    // the Reverberant (ADR-0017 rung 2): summoned by SOLVING the pedestal puzzle,
    // not an altar — so no altar/monument/Ward. Its arena is the open puzzle court.
    reverb: {
      arena: REVERB_ARENA,
      home: REVERB_HOME,
      altar: REVERB_HOME, // vestigial (never used — no altar interaction)
      monument: REVERB_HOME, // vestigial
      sealGate: [], // no Ward — the boss rises inside the open court
    },
  },
  // ADR-0017 rung 2: the Hushdark's pedestal-vaults (echo-coverage → weekly cache)
  hushdarkVaults,
  // the memorial plinth where a master leaves a permanent named greeting shade
  hushdarkMemorial,
};

const outDir = path.resolve(import.meta.dirname, '../public/map');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'jungle-map.json'), JSON.stringify(tiledMap));
fs.writeFileSync(path.join(outDir, 'world-data.json'), JSON.stringify(worldData));

const counts: Record<string, number> = {};
for (const n of keptNodes) counts[n.type] = (counts[n.type] ?? 0) + 1;
console.log(`Map written: ${W}x${H}, ${keptNodes.length} nodes`, counts);
console.log(`Secrets: ${tablets.length} tablets, ${gate.length} gate tiles, ${treasureSpots.length} treasure spots`);
console.log(`Arena at (${ARENA.x},${ARENA.y}) ${ARENA.w}x${ARENA.h}, seal gate ${SEAL_GATE.map((g) => `${g.tx},${g.ty}`).join(' ')}`);
console.log(`Zones: ${zones.map((z) => z.name).join(', ')}`);
console.log(
  `Districts: ${districts
    .map((d) => `${d.id} @ ${d.rect.x},${d.rect.y} ${d.rect.w}x${d.rect.h} · gate ${d.gate.worldTx},${d.gate.worldTy} ⇄ ${d.gate.districtTx},${d.gate.districtTy}`)
    .join('; ')}`,
);
